// <auto-generated />
namespace WebApplicationSAmpleExam.Migrations.attendDb
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbinitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbinitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101507314_db initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
